# Generated by Django 4.0.3 on 2022-08-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_options_alter_jobhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
