# Generated by Django 4.0.3 on 2022-08-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhistory',
            name='description',
        ),
    ]
